### ISSUE TITLE
[Proposal] Use pickle instead of using serialized parameter

### ISSUE THREAD

**Issue by kitagry** [m3dev/kannon#12]
Instead of serializing TaskParameter, how about making the task itself pickle to execute? I am thinking of the following execution procedure.

1. Make the task into a pickle and save it in gokart's cache space. (Currently, the cache space should be shared between master and child jobs.)
2. Specify the path to the pickle file in job's args and call it.

This should solve the following problems.

* The parameters to serialize are accurate.
  * e.x) #8 
  * [ParameterVisibility.PRIVATE](https://luigi.readthedocs.io/en/stable/parameters.html#parameter-visibility) params aren't serialized.
* The task itself does not need to be imported by a child job.

**Comment by maronuu** [comment]
Thanks for a great proposal!
I will work on it soon, before completion of #5
