### ISSUE TITLE
Release plan for v0.1.2

### ISSUE THREAD

**Issue by maronuu** [m3dev/kannon#19]
## What
Since #17 requires the latest version of kannon to be installed via `pip install kannon`, I'd like to release v0.1.2 in 2023/04/13 or 14, which enables to make progress on #17 and get it ready for review,

**Comment by maronuu** [comment]
# Release Draft

## What's Changed
* Support k8s persistent volumes as a shared cache by @maronuu in https://github.com/m3dev/kannon/pull/6
* flatten requires by @yokomotod in https://github.com/m3dev/kannon/pull/10
* Update README by @maronuu in https://github.com/m3dev/kannon/pull/9
* Fix lint setting by @kitagry in https://github.com/m3dev/kannon/pull/11
* Fix not wait first bullet bug by @maronuu in https://github.com/m3dev/kannon/pull/14
* lint github actions by @yokomotod in https://github.com/m3dev/kannon/pull/13
* add CODEOWNERS by @yokomotod in https://github.com/m3dev/kannon/pull/16
* Fix env and command replacement by @maronuu in https://github.com/m3dev/kannon/pull/15

## New Contributors
* @kitagry made their first contribution in https://github.com/m3dev/kannon/pull/11

**Full Changelog**: https://github.com/m3dev/kannon/compare/0.1.1...0.1.2

**Comment by maronuu** [comment]
@kitagry @yokomotod 
In addition, #18 will be included.

How do you think of this release?

**Comment by yokomotod** [comment]
LGTM!

**Comment by kitagry** [comment]
LGTM👍

**Comment by hirosassa** [comment]
Looks good!👍
