### ISSUE TITLE
[Proposal] Enable Discussions

### ISSUE THREAD

**Issue by yokomotod** [m3dev/kannon#25]
Discussion is currently disabled, are you interested in turning it on? @maronuu @kitagry 

https://github.com/m3dev/kannon/discussions/landing 

I've never managed a repository with it, so I don't know how good the experience would be, though...especially, I'm not sure whether issues is enough or not.

----

At least, we can subscribe it on slack with official integration. (some old articles say it's not yet supported)

https://github.com/orgs/community/discussions/2844#discussioncomment-2061814

**Comment by kitagry** [comment]
we can use discussion now? https://github.com/m3dev/kannon/discussions

I don't know what is different between issue and discussion. But I agree to make discussion enabled.

**Comment by maronuu** [comment]
I don't know well on the discussion feature, but it seems good.

**Comment by yokomotod** [comment]
thanks! let's try to use.
